---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	normalize_input(normalize_input)
	fast_signal_scan(fast_signal_scan)
	adaptive_router(adaptive_router)
	low_risk_gate(low_risk_gate)
	fast_exit_decision(fast_exit_decision)
	risk_type_branch_analysis(risk_type_branch_analysis)
	deterministic_decision_engine(deterministic_decision_engine)
	validation_gate(validation_gate)
	conflict_validator(conflict_validator)
	apply_validation_decision(apply_validation_decision)
	final_context_agents(final_context_agents)
	report_generator(report_generator)
	__end__([<p>__end__</p>]):::last
	__start__ --> normalize_input;
	normalize_input --> fast_signal_scan;
	fast_signal_scan --> adaptive_router;
	adaptive_router -. &nbsp;fast_exit&nbsp; .-> low_risk_gate;
	adaptive_router -. &nbsp;deep_analysis&nbsp; .-> risk_type_branch_analysis;
	low_risk_gate -. &nbsp;fast_exit confirmed&nbsp; .-> fast_exit_decision;
	low_risk_gate -. &nbsp;漏判修正 / escalate high risk&nbsp; .-> risk_type_branch_analysis;
	fast_exit_decision --> final_context_agents;
	risk_type_branch_analysis --> deterministic_decision_engine;
	deterministic_decision_engine --> validation_gate;
	validation_gate -. &nbsp;need_validation&nbsp; .-> conflict_validator;
	validation_gate -. &nbsp;no_validation&nbsp; .-> final_context_agents;
	conflict_validator --> apply_validation_decision;
	apply_validation_decision --> final_context_agents;
	final_context_agents --> report_generator;
	report_generator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
