---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	normalize_input(normalize_input)
	fast_signal_scan(fast_signal_scan)
	adaptive_orchestrator(adaptive_orchestrator)
	scenario_router_and_contracts(scenario_router_and_contracts)
	targeted_evidence_extractor(targeted_evidence_extractor)
	parallel_scenario_evaluators(parallel_scenario_evaluators)
	decision_engine(decision_engine)
	conflict_validator(conflict_validator)
	apply_validation_decision(apply_validation_decision)
	report_generator(report_generator)
	__end__([<p>__end__</p>]):::last
	__start__ --> normalize_input;
	adaptive_orchestrator -. &nbsp;fast_exit&nbsp; .-> report_generator;
	adaptive_orchestrator -. &nbsp;analysis&nbsp; .-> scenario_router_and_contracts;
	apply_validation_decision --> report_generator;
	conflict_validator --> apply_validation_decision;
	decision_engine -. &nbsp;need_validation&nbsp; .-> conflict_validator;
	decision_engine -. &nbsp;no_validation&nbsp; .-> report_generator;
	fast_signal_scan --> adaptive_orchestrator;
	normalize_input --> fast_signal_scan;
	parallel_scenario_evaluators --> decision_engine;
	scenario_router_and_contracts --> targeted_evidence_extractor;
	targeted_evidence_extractor --> parallel_scenario_evaluators;
	report_generator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
